author: qkuldo
title: my personal website
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  social_links: 
    - title: Github
      icon: github
      url: "https://github.com/qkuldo"