remote_theme: pages-themes/minimal@v0.2.0
author: qkuldo
title: my personal website
description: This is my place on the internet, where I can talk about stuff (usually about my programming projects).I usually post at the last week of each month, and I have a break from posting every December.